<template>
  <main class="container"><div class="user-table"><div class="header-section table-panel-header"><h2>Activity Logs</h2><button type="button" @click="loadLogs">Refresh</button></div>
    <div class="filter-container"><div class="searchbar"><input type="search" placeholder="Search actions, entities, or users" v-model="searchQuery" aria-label="Search activity logs"><button v-if="searchQuery" type="button" class="search-clear" @click="searchQuery=''" aria-label="Clear search"><i class="fi fi-br-cross-small"></i></button><i v-else class="fi fi-br-search" aria-hidden="true"></i></div><div class="dropdown"><select v-model="selectedActor" aria-label="Filter by performed by"><option value="all">All performers</option><option v-for="actor in actors" :key="actor" :value="actor">{{ actor }}</option></select><select v-model="selectedAction" aria-label="Filter by action"><option value="all">All actions</option><option v-for="action in actions" :key="action" :value="action">{{ action }}</option></select><select v-model="selectedTime" aria-label="Filter by time"><option value="all">All time</option><option value="today">Today</option><option value="week">Last 7 days</option><option value="month">Last 30 days</option></select></div></div>
    <p v-if="errorMessage" class="alert-danger">{{ errorMessage }}</p><table><thead><tr><th>Action</th><th>Entity</th><th>Performed By</th><th>Date & Time</th></tr></thead><tbody><tr v-for="log in paginatedLogs" :key="log.log_id"><td>{{ log.action }}</td><td>{{ log.entity_type }}<template v-if="log.entity_id"> #{{ log.entity_id }}</template></td><td>{{ log.actor_username || 'System' }}</td><td>{{ formatDate(log.created_at) }}</td></tr><tr v-if="!filteredLogs.length"><td colspan="4" class="empty-state">No matching activity logs.</td></tr></tbody></table><div class="table-panel-footer"><span>Showing {{ pageStart }}-{{ pageEnd }} of {{ filteredLogs.length }} logs</span><div class="pagination"><button type="button" class="pagination-arrow" :disabled="currentPage===1" @click="currentPage--">&lsaquo;</button><span class="pagination-label">Page</span><button v-for="page in pageCount" :key="page" type="button" class="pagination-page" :class="{active:currentPage===page}" @click="currentPage=page">{{ page }}</button><span class="pagination-total">of {{ pageCount }}</span><button type="button" class="pagination-arrow" :disabled="currentPage===pageCount" @click="currentPage++">&rsaquo;</button></div></div>
  </div></main>
</template>
<script>
import { supabase } from '@/utils/supabase.js';
export default { name:'ActivityLogs', data:()=>({logs:[],currentPage:1,pageSize:5,searchQuery:'',selectedActor:'all',selectedAction:'all',selectedTime:'all',errorMessage:''}), computed:{actors(){return [...new Set(this.logs.map(log=>log.actor_username).filter(Boolean))].sort();},actions(){return [...new Set(this.logs.map(log=>log.action).filter(Boolean))].sort();},filteredLogs(){const q=this.searchQuery.trim().toLowerCase();const now=Date.now();const ranges={today:86400000,week:604800000,month:2592000000};return this.logs.filter(log=>{const text=[log.action,log.entity_type,log.entity_id,log.actor_username].join(' ').toLowerCase();const date=new Date(log.created_at).getTime();return(!q||text.includes(q))&&(this.selectedActor==='all'||log.actor_username===this.selectedActor)&&(this.selectedAction==='all'||log.action===this.selectedAction)&&(this.selectedTime==='all'||now-date<=ranges[this.selectedTime]);});},paginatedLogs(){const start=(this.currentPage-1)*this.pageSize;return this.filteredLogs.slice(start,start+this.pageSize);},pageCount(){return Math.max(1,Math.ceil(this.filteredLogs.length/this.pageSize));},pageStart(){return this.filteredLogs.length?(this.currentPage-1)*this.pageSize+1:0;},pageEnd(){return Math.min(this.currentPage*this.pageSize,this.filteredLogs.length);}},watch:{searchQuery(){this.currentPage=1;},selectedActor(){this.currentPage=1;},selectedAction(){this.currentPage=1;},selectedTime(){this.currentPage=1;}},mounted(){this.loadLogs();},methods:{async loadLogs(){const{data,error}=await supabase.rpc('get_audit_logs',{p_limit:100});if(error)this.errorMessage=error.message||'Unable to load activity logs.';else{this.logs=data||[];this.currentPage=1;}},formatDate(value){return value?new Date(value).toLocaleString():'—';}}};
</script>
<style src="@/assets/CSS/superadmin.css"></style>
